import { NgModule } from '@angular/core';

import {FlexLayoutModule} from '@angular/flex-layout';
import {
    MatToolbarModule,
    MatIconModule,
    MatSidenavModule,
    MatButtonModule,
    MatMenuModule,
    MatCheckboxModule,
    MatInputModule,
    MatCardModule,
    MatSliderModule,
    MatRadioModule,
    MatSelectModule,
    MatFormFieldModule,
    MatSlideToggleModule,
    MatListModule,
    MatTreeModule,
    MatTableModule,
    MatDialogModule,
    MatPaginatorModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatGridListModule,
    MatTabsModule
} from '@angular/material';
import {LayoutModule} from '@angular/cdk/layout';

@NgModule({
    imports: [
        LayoutModule,
        FlexLayoutModule,
        MatToolbarModule,
        MatIconModule,
        MatSidenavModule,
        MatButtonModule,
        MatMenuModule,
        MatCheckboxModule,
        MatCardModule,
        MatInputModule,
        MatSliderModule,
        MatRadioModule,
        MatSelectModule,
        MatFormFieldModule,
        MatSlideToggleModule,
        MatListModule,
        MatTreeModule,
        MatToolbarModule, 
        MatIconModule, 
        MatSidenavModule, 
        MatButtonModule,
        MatMenuModule,
        MatFormFieldModule,
        MatInputModule,
        MatListModule,
        MatSelectModule,
        MatSlideToggleModule,
        MatTableModule,
        MatDialogModule,
        MatPaginatorModule,
        MatTooltipModule,
        MatSnackBarModule,
        MatExpansionModule,
        MatGridListModule,
        MatTabsModule
    ],
    exports: [
        LayoutModule,
        FlexLayoutModule,
        MatToolbarModule,
        MatIconModule,
        MatSidenavModule,
        MatButtonModule,
        MatMenuModule,
        MatCheckboxModule,
        MatCardModule,
        MatInputModule,
        MatSliderModule,
        MatRadioModule,
        MatSelectModule,
        MatFormFieldModule,
        MatSlideToggleModule,
        MatListModule,
        MatTreeModule,
        MatTableModule,
        MatDialogModule,
        MatPaginatorModule,
        MatTooltipModule,
        MatSnackBarModule,
        MatExpansionModule,
        MatGridListModule,
        MatTabsModule
    ],
})
export class MaterialModule {}
